/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buysmart.view;

/**
 *
 * @author fahmi
 */
public class AdminProductAdd extends javax.swing.JFrame {

    /**
     * Creates new form AdminProductAdd
     */
    public AdminProductAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminProductCardPanel = new javax.swing.JPanel();
        AdminDescription = new javax.swing.JTextField();
        AdminDescriptionLabel = new javax.swing.JLabel();
        AdminProductPriceLabel = new javax.swing.JLabel();
        AdminProductCategoryLabel = new javax.swing.JLabel();
        AdminImageLabel = new javax.swing.JLabel();
        AdminPriceIndicator = new javax.swing.JLabel();
        AdminProductCategory = new javax.swing.JComboBox<>();
        AdminProductImagePath = new javax.swing.JTextField();
        AdminJustImage = new javax.swing.JLabel();
        AdminProductPrice = new javax.swing.JTextField();
        AdminProductAddButton = new javax.swing.JButton();
        AdminAddProductPanel = new javax.swing.JPanel();
        AdminBackButton = new javax.swing.JButton();
        AdminLogout = new javax.swing.JButton();
        AdminLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminProductCardPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 3, true));

        AdminDescription.setEditable(false);
        AdminDescription.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AdminDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminDescriptionActionPerformed(evt);
            }
        });

        AdminDescriptionLabel.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 18)); // NOI18N
        AdminDescriptionLabel.setText("description :");

        AdminProductPriceLabel.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 18)); // NOI18N
        AdminProductPriceLabel.setText("price :");

        AdminProductCategoryLabel.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 18)); // NOI18N
        AdminProductCategoryLabel.setText("category :");

        AdminImageLabel.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 18)); // NOI18N
        AdminImageLabel.setText("Image Path :");

        AdminPriceIndicator.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 18)); // NOI18N
        AdminPriceIndicator.setText("Rs.");

        AdminProductCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Products", "Computers" }));

        AdminProductImagePath.setEditable(false);
        AdminProductImagePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminProductImagePathActionPerformed(evt);
            }
        });

        AdminJustImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/imageloader (1).png"))); // NOI18N

        AdminProductPrice.setEditable(false);

        AdminProductAddButton.setBackground(new java.awt.Color(153, 204, 255));
        AdminProductAddButton.setText("Add Product");

        javax.swing.GroupLayout AdminProductCardPanelLayout = new javax.swing.GroupLayout(AdminProductCardPanel);
        AdminProductCardPanel.setLayout(AdminProductCardPanelLayout);
        AdminProductCardPanelLayout.setHorizontalGroup(
            AdminProductCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminProductCardPanelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(AdminProductCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminImageLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AdminProductCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(AdminDescriptionLabel)
                        .addComponent(AdminProductPriceLabel)
                        .addComponent(AdminProductCategoryLabel)))
                .addGap(30, 30, 30)
                .addGroup(AdminProductCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminProductCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AdminProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminProductCardPanelLayout.createSequentialGroup()
                            .addComponent(AdminPriceIndicator)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AdminProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AdminProductCardPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(AdminProductCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminJustImage)
                            .addComponent(AdminDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminProductImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AdminProductCardPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(AdminProductAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(93, 93, 93))
        );
        AdminProductCardPanelLayout.setVerticalGroup(
            AdminProductCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminProductCardPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(AdminProductCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminProductCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminProductCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminPriceIndicator)
                    .addComponent(AdminProductPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(AdminProductCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminDescriptionLabel))
                .addGap(18, 18, 18)
                .addComponent(AdminJustImage, javax.swing.GroupLayout.PREFERRED_SIZE, 178, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(AdminProductCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminProductImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminImageLabel))
                .addGap(18, 18, 18)
                .addComponent(AdminProductAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        AdminAddProductPanel.setBackground(new java.awt.Color(204, 204, 204));

        AdminBackButton.setBackground(new java.awt.Color(51, 204, 255));
        AdminBackButton.setText("Back");
        AdminBackButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        AdminBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminBackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminBackButtonMouseExited(evt);
            }
        });
        AdminBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBackButtonActionPerformed(evt);
            }
        });

        AdminLogout.setBackground(new java.awt.Color(102, 204, 255));
        AdminLogout.setText("Logout");
        AdminLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        AdminLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminLogoutMouseExited(evt);
            }
        });
        AdminLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLogoutActionPerformed(evt);
            }
        });

        AdminLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/logo2 (1).png"))); // NOI18N

        javax.swing.GroupLayout AdminAddProductPanelLayout = new javax.swing.GroupLayout(AdminAddProductPanel);
        AdminAddProductPanel.setLayout(AdminAddProductPanelLayout);
        AdminAddProductPanelLayout.setHorizontalGroup(
            AdminAddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminAddProductPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(AdminBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(AdminLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(AdminLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        AdminAddProductPanelLayout.setVerticalGroup(
            AdminAddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminAddProductPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(AdminAddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminLogo)
                    .addComponent(AdminLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminAddProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminProductCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AdminAddProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(AdminProductCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminDescriptionActionPerformed

    private void AdminBackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminBackButtonMouseEntered
        
    }//GEN-LAST:event_AdminBackButtonMouseEntered

    private void AdminBackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminBackButtonMouseExited
        
    }//GEN-LAST:event_AdminBackButtonMouseExited

    private void AdminBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminBackButtonActionPerformed

    private void AdminLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLogoutMouseEntered
        
    }//GEN-LAST:event_AdminLogoutMouseEntered

    private void AdminLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLogoutMouseExited
        
    }//GEN-LAST:event_AdminLogoutMouseExited

    private void AdminLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminLogoutActionPerformed

    private void AdminProductImagePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminProductImagePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminProductImagePathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProductAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProductAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProductAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProductAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProductAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminAddProductPanel;
    private javax.swing.JButton AdminBackButton;
    private javax.swing.JTextField AdminDescription;
    private javax.swing.JLabel AdminDescriptionLabel;
    private javax.swing.JLabel AdminImageLabel;
    private javax.swing.JLabel AdminJustImage;
    private javax.swing.JLabel AdminLogo;
    private javax.swing.JButton AdminLogout;
    private javax.swing.JLabel AdminPriceIndicator;
    private javax.swing.JButton AdminProductAddButton;
    private javax.swing.JPanel AdminProductCardPanel;
    private javax.swing.JComboBox<String> AdminProductCategory;
    private javax.swing.JLabel AdminProductCategoryLabel;
    private javax.swing.JTextField AdminProductImagePath;
    private javax.swing.JTextField AdminProductPrice;
    private javax.swing.JLabel AdminProductPriceLabel;
    // End of variables declaration//GEN-END:variables
}
