/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buysmart.view;

import buysmart.controller.computersController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author fahmi
 */
public class ComputersView extends javax.swing.JFrame {
    private computersController controller;
    private JButton[] cartButtons;

    /**
     * Creates new form ComputersView
     */
    public ComputersView() {
        initComponents();
        
        try {
            controller = new computersController(this, "av@gmail.com");
            controller.loadComputers();
        } catch (Exception e) {
            System.err.println("Error initializing ComputersController: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to load Computers View: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        cartButtons = new JButton[] {
            ProductAddToCartButton, ProductAddToCartButton1, ProductAddToCartButton2,
            ProductAddToCartButton3, ProductAddToCartButton4
        };
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComputersPanel = new javax.swing.JPanel();
        ComputersViewPanel1 = new javax.swing.JPanel();
        ComputersPicture1 = new javax.swing.JLabel();
        ProductAddToCartButton = new javax.swing.JButton();
        ComputersPrice1 = new javax.swing.JLabel();
        ComputersDescription1 = new javax.swing.JLabel();
        ComputersViewPanel2 = new javax.swing.JPanel();
        ComputersPicture2 = new javax.swing.JLabel();
        ProductAddToCartButton1 = new javax.swing.JButton();
        ComputersPrice2 = new javax.swing.JLabel();
        ComputersDescription2 = new javax.swing.JLabel();
        ComputersViewPanel3 = new javax.swing.JPanel();
        ComputersPicture3 = new javax.swing.JLabel();
        ProductAddToCartButton2 = new javax.swing.JButton();
        ComputersPrice3 = new javax.swing.JLabel();
        ComputersDescription3 = new javax.swing.JLabel();
        ComputersViewPanel4 = new javax.swing.JPanel();
        ComputersPicture4 = new javax.swing.JLabel();
        ProductAddToCartButton3 = new javax.swing.JButton();
        ComputersPrice4 = new javax.swing.JLabel();
        ComputersDescription4 = new javax.swing.JLabel();
        ComputersViewPanel5 = new javax.swing.JPanel();
        ComputersPicture5 = new javax.swing.JLabel();
        ProductAddToCartButton4 = new javax.swing.JButton();
        ComputersPrice5 = new javax.swing.JLabel();
        ComputersDescription5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComputersPanel.setBackground(new java.awt.Color(204, 204, 204));

        ComputersPicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/Lenovo ThinkCentre1.png"))); // NOI18N
        ComputersPicture1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductAddToCartButton.setBackground(new java.awt.Color(153, 204, 255));
        ProductAddToCartButton.setText("Add To Card");

        ComputersPrice1.setBackground(new java.awt.Color(255, 255, 255));
        ComputersPrice1.setText("jLabel2");

        ComputersDescription1.setText("jLabel2");

        javax.swing.GroupLayout ComputersViewPanel1Layout = new javax.swing.GroupLayout(ComputersViewPanel1);
        ComputersViewPanel1.setLayout(ComputersViewPanel1Layout);
        ComputersViewPanel1Layout.setHorizontalGroup(
            ComputersViewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComputersViewPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ComputersViewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComputersViewPanel1Layout.createSequentialGroup()
                        .addGroup(ComputersViewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ComputersDescription1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ComputersViewPanel1Layout.createSequentialGroup()
                                .addComponent(ComputersPrice1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ProductAddToCartButton)))
                        .addGap(16, 16, 16))
                    .addGroup(ComputersViewPanel1Layout.createSequentialGroup()
                        .addComponent(ComputersPicture1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        ComputersViewPanel1Layout.setVerticalGroup(
            ComputersViewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersViewPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ComputersPicture1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComputersDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ComputersViewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductAddToCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComputersPrice1))
                .addGap(36, 36, 36))
        );

        ComputersPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/HP Pro 400 G91.png"))); // NOI18N
        ComputersPicture2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductAddToCartButton1.setBackground(new java.awt.Color(153, 204, 255));
        ProductAddToCartButton1.setText("Add To Cart");

        ComputersPrice2.setBackground(new java.awt.Color(255, 255, 255));
        ComputersPrice2.setText("jLabel2");

        ComputersDescription2.setText("jLabel2");

        javax.swing.GroupLayout ComputersViewPanel2Layout = new javax.swing.GroupLayout(ComputersViewPanel2);
        ComputersViewPanel2.setLayout(ComputersViewPanel2Layout);
        ComputersViewPanel2Layout.setHorizontalGroup(
            ComputersViewPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersViewPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComputersViewPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComputersDescription2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ComputersViewPanel2Layout.createSequentialGroup()
                        .addGroup(ComputersViewPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComputersPicture2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addGroup(ComputersViewPanel2Layout.createSequentialGroup()
                                .addComponent(ComputersPrice2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ProductAddToCartButton1)))
                        .addContainerGap())))
        );
        ComputersViewPanel2Layout.setVerticalGroup(
            ComputersViewPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersViewPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ComputersPicture2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComputersDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(ComputersViewPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductAddToCartButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComputersPrice2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        ComputersPicture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/Dell Wyse 5070 (1).png"))); // NOI18N
        ComputersPicture3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductAddToCartButton2.setBackground(new java.awt.Color(153, 204, 255));
        ProductAddToCartButton2.setText("Add To Cart");

        ComputersPrice3.setBackground(new java.awt.Color(255, 255, 255));
        ComputersPrice3.setText("jLabel2");

        ComputersDescription3.setText("jLabel2");

        javax.swing.GroupLayout ComputersViewPanel3Layout = new javax.swing.GroupLayout(ComputersViewPanel3);
        ComputersViewPanel3.setLayout(ComputersViewPanel3Layout);
        ComputersViewPanel3Layout.setHorizontalGroup(
            ComputersViewPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersViewPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ComputersViewPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComputersViewPanel3Layout.createSequentialGroup()
                        .addComponent(ComputersPicture3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(ComputersViewPanel3Layout.createSequentialGroup()
                        .addGroup(ComputersViewPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ComputersDescription3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ComputersViewPanel3Layout.createSequentialGroup()
                                .addComponent(ComputersPrice3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ProductAddToCartButton2)))
                        .addGap(16, 16, 16))))
        );
        ComputersViewPanel3Layout.setVerticalGroup(
            ComputersViewPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersViewPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComputersPicture3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ComputersDescription3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(ComputersViewPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComputersPrice3)
                    .addComponent(ProductAddToCartButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        ComputersPicture4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/HP Chromebook1 .png"))); // NOI18N
        ComputersPicture4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductAddToCartButton3.setBackground(new java.awt.Color(153, 204, 255));
        ProductAddToCartButton3.setText("Add To Cart");

        ComputersPrice4.setBackground(new java.awt.Color(255, 255, 255));
        ComputersPrice4.setText("jLabel2");

        ComputersDescription4.setText("jLabel2");

        javax.swing.GroupLayout ComputersViewPanel4Layout = new javax.swing.GroupLayout(ComputersViewPanel4);
        ComputersViewPanel4.setLayout(ComputersViewPanel4Layout);
        ComputersViewPanel4Layout.setHorizontalGroup(
            ComputersViewPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersViewPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComputersViewPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComputersViewPanel4Layout.createSequentialGroup()
                        .addComponent(ComputersPicture4, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(ComputersViewPanel4Layout.createSequentialGroup()
                        .addGroup(ComputersViewPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ComputersViewPanel4Layout.createSequentialGroup()
                                .addComponent(ComputersPrice4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ProductAddToCartButton3))
                            .addComponent(ComputersDescription4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))))
        );
        ComputersViewPanel4Layout.setVerticalGroup(
            ComputersViewPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersViewPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComputersPicture4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComputersDescription4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(ComputersViewPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComputersPrice4)
                    .addComponent(ProductAddToCartButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        ComputersPicture5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/MacBook Air M41.png"))); // NOI18N
        ComputersPicture5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductAddToCartButton4.setBackground(new java.awt.Color(153, 204, 255));
        ProductAddToCartButton4.setText("Add To Cart");

        ComputersPrice5.setBackground(new java.awt.Color(255, 255, 255));
        ComputersPrice5.setText("jLabel2");

        ComputersDescription5.setText("jLabel2");

        javax.swing.GroupLayout ComputersViewPanel5Layout = new javax.swing.GroupLayout(ComputersViewPanel5);
        ComputersViewPanel5.setLayout(ComputersViewPanel5Layout);
        ComputersViewPanel5Layout.setHorizontalGroup(
            ComputersViewPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersViewPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ComputersViewPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComputersViewPanel5Layout.createSequentialGroup()
                        .addComponent(ComputersPicture5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(ComputersViewPanel5Layout.createSequentialGroup()
                        .addGroup(ComputersViewPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComputersDescription5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ComputersViewPanel5Layout.createSequentialGroup()
                                .addComponent(ComputersPrice5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ProductAddToCartButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
        );
        ComputersViewPanel5Layout.setVerticalGroup(
            ComputersViewPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersViewPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComputersPicture5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComputersDescription5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ComputersViewPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductAddToCartButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComputersPrice5))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ComputersPanelLayout = new javax.swing.GroupLayout(ComputersPanel);
        ComputersPanel.setLayout(ComputersPanelLayout);
        ComputersPanelLayout.setHorizontalGroup(
            ComputersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(ComputersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComputersViewPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComputersViewPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(ComputersViewPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ComputersViewPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ComputersViewPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        ComputersPanelLayout.setVerticalGroup(
            ComputersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ComputersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComputersViewPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComputersViewPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ComputersViewPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComputersViewPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(ComputersViewPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1087, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ComputersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ComputersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputersView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ComputersDescription1;
    private javax.swing.JLabel ComputersDescription2;
    private javax.swing.JLabel ComputersDescription3;
    private javax.swing.JLabel ComputersDescription4;
    private javax.swing.JLabel ComputersDescription5;
    private javax.swing.JPanel ComputersPanel;
    private javax.swing.JLabel ComputersPicture1;
    private javax.swing.JLabel ComputersPicture2;
    private javax.swing.JLabel ComputersPicture3;
    private javax.swing.JLabel ComputersPicture4;
    private javax.swing.JLabel ComputersPicture5;
    private javax.swing.JLabel ComputersPrice1;
    private javax.swing.JLabel ComputersPrice2;
    private javax.swing.JLabel ComputersPrice3;
    private javax.swing.JLabel ComputersPrice4;
    private javax.swing.JLabel ComputersPrice5;
    private javax.swing.JPanel ComputersViewPanel1;
    private javax.swing.JPanel ComputersViewPanel2;
    private javax.swing.JPanel ComputersViewPanel3;
    private javax.swing.JPanel ComputersViewPanel4;
    private javax.swing.JPanel ComputersViewPanel5;
    private javax.swing.JButton ProductAddToCartButton;
    private javax.swing.JButton ProductAddToCartButton1;
    private javax.swing.JButton ProductAddToCartButton2;
    private javax.swing.JButton ProductAddToCartButton3;
    private javax.swing.JButton ProductAddToCartButton4;
    // End of variables declaration//GEN-END:variables


    // Getter methods for UI components
    
    //1st computers
    public JLabel getComputersPicture1() {
        return ComputersPicture1;
    }
    

    public JLabel getComputersDescription1() {
        return ComputersDescription1;
    }

    public JLabel getComputersPrice1() {
        return ComputersPrice1;
    }

    public JButton getProductAddToCartButton() {
        return ProductAddToCartButton;
    }

    //2nd computers
    
    public JLabel getComputersPicture2() {
        return ComputersPicture2;
    }
    
    public JLabel getComputersDescription2() {
        return ComputersDescription2;
    }

    public JLabel getComputersPrice2() {
        return ComputersPrice2;
    }

    public JButton getProductAddToCartButton1() {
        return ProductAddToCartButton1;
    }

    //3rd computers
    

    public JLabel getComputersPicture3() {
        return ComputersPicture3;
    }
    public JLabel getComputersDescription3() {
        return ComputersDescription3;
    }

    public JLabel getComputersPrice3() {
        return ComputersPrice3;
    }

    public JButton getProductAddToCartButton2() {
        return ProductAddToCartButton2;
    }

    //4th computers
    
    public JLabel getComputersPicture4() {
        return ComputersPicture4;
    }
    
    public JLabel getComputersDescription4() {
        return ComputersDescription4;
    }

    public JLabel getComputersPrice4() {
        return ComputersPrice4;
    }

    public JButton getProductAddToCartButton3() {
        return ProductAddToCartButton3;
    }

    //5th computers
    
    public JLabel getComputersPicture5() {
        return ComputersPicture5;
    }
    
    public JLabel getComputersDescription5() {
        return ComputersDescription5;
    }

    public JLabel getComputersPrice5() {
        return ComputersPrice5;
    }

    public JButton getProductAddToCartButton4() {
        return ProductAddToCartButton4;
    }

}
