/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buysmart.view;

import java.awt.Color;
import javax.swing.JFrame;


/**
 *
 * @author fahmi
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        logoutPanel1 = new javax.swing.JPanel();
        buttonLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dashboardLogo = new javax.swing.JLabel();
        statusPanel2 = new javax.swing.JPanel();
        buttonPanel3 = new javax.swing.JPanel();
        buttonSports = new javax.swing.JButton();
        buttonToys = new javax.swing.JButton();
        buttonBeauties = new javax.swing.JButton();
        buttonBooks = new javax.swing.JButton();
        buttonClothing = new javax.swing.JButton();
        ButtonComputers = new javax.swing.JButton();
        buttonElectronics = new javax.swing.JButton();
        buttonAll = new javax.swing.JButton();
        wishlistIcon = new javax.swing.JLabel();
        orderlistIcon = new javax.swing.JLabel();
        cartIcon = new javax.swing.JLabel();
        searchIcon = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        productPanel1 = new javax.swing.JPanel();
        Product8MainPanel = new javax.swing.JPanel();
        product8Panel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        product8Description = new javax.swing.JLabel();
        Product8price = new javax.swing.JLabel();
        product8rating = new javax.swing.JLabel();
        product8BuyButoon = new javax.swing.JButton();
        Product8AddtocarButton = new javax.swing.JButton();
        Product7MainPanel = new javax.swing.JPanel();
        product7Panel = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        product7Description = new javax.swing.JLabel();
        Product7price = new javax.swing.JLabel();
        product7rating = new javax.swing.JLabel();
        product7BuyButoon = new javax.swing.JButton();
        Product7AddtocarButton = new javax.swing.JButton();
        Product6MainPanel = new javax.swing.JPanel();
        product6Panel = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        product6Description = new javax.swing.JLabel();
        Product6price = new javax.swing.JLabel();
        product6rating = new javax.swing.JLabel();
        product6BuyButoon = new javax.swing.JButton();
        Product6AddtocarButton = new javax.swing.JButton();
        Product5MainPanel = new javax.swing.JPanel();
        product5Panel = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        product5Description = new javax.swing.JLabel();
        Product5price = new javax.swing.JLabel();
        product5rating = new javax.swing.JLabel();
        Product5AddtocarButton = new javax.swing.JButton();
        product5BuyButoon = new javax.swing.JButton();
        Product2MainPanel = new javax.swing.JPanel();
        product2Panel = new javax.swing.JPanel();
        product2pic = new javax.swing.JLabel();
        product2Description = new javax.swing.JLabel();
        product2price = new javax.swing.JLabel();
        product2rating = new javax.swing.JLabel();
        Product2AddtocarButton = new javax.swing.JButton();
        product2BuyButoon = new javax.swing.JButton();
        Product4MainPanel = new javax.swing.JPanel();
        product4Panel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        product4Description = new javax.swing.JLabel();
        Product4price = new javax.swing.JLabel();
        product4rating = new javax.swing.JLabel();
        Product4AddtocarButton = new javax.swing.JButton();
        product4BuyButoon = new javax.swing.JButton();
        Product3MainPanel = new javax.swing.JPanel();
        Product3Panel = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        product3pic = new javax.swing.JLabel();
        product3Description = new javax.swing.JLabel();
        Product3price = new javax.swing.JLabel();
        product3rating = new javax.swing.JLabel();
        Product3AddtocarButton = new javax.swing.JButton();
        product3BuyButoon = new javax.swing.JButton();
        Product1MainPanel1 = new javax.swing.JPanel();
        product1Panel1 = new javax.swing.JPanel();
        product2pic1 = new javax.swing.JLabel();
        product1Description = new javax.swing.JLabel();
        Product1price = new javax.swing.JLabel();
        product1rating = new javax.swing.JLabel();
        Product1AddtocarButton = new javax.swing.JButton();
        product1BuyButoon = new javax.swing.JButton();
        rightclickPanel1 = new javax.swing.JPanel();
        rightclickIcon = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setText("Black Tshirt Cotton Men");

        jLabel16.setText("Rs. 800");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_529639780_Preview (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel17)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel25.setText("Black Tshirt Cotton Men");

        jLabel26.setText("Rs. 800");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_529639780_Preview (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel26))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel25))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel27)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(15, 15, 15)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        logoutPanel1.setBackground(new java.awt.Color(204, 204, 204));

        buttonLogout.setBackground(new java.awt.Color(153, 204, 255));
        buttonLogout.setText("Logout");
        buttonLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/user (1).png"))); // NOI18N

        dashboardLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/logo40.png"))); // NOI18N

        javax.swing.GroupLayout logoutPanel1Layout = new javax.swing.GroupLayout(logoutPanel1);
        logoutPanel1.setLayout(logoutPanel1Layout);
        logoutPanel1Layout.setHorizontalGroup(
            logoutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboardLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutPanel1Layout.setVerticalGroup(
            logoutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(logoutPanel1Layout.createSequentialGroup()
                        .addComponent(dashboardLogo)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(logoutPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buttonPanel3.setBackground(new java.awt.Color(51, 153, 255));

        buttonSports.setBackground(new java.awt.Color(153, 204, 255));
        buttonSports.setText("Sports");
        buttonSports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buttonSports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSportsMouseExited(evt);
            }
        });
        buttonSports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSportsActionPerformed(evt);
            }
        });

        buttonToys.setBackground(new java.awt.Color(153, 204, 255));
        buttonToys.setText("Toys");
        buttonToys.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buttonToys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonToysMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonToysMouseExited(evt);
            }
        });

        buttonBeauties.setBackground(new java.awt.Color(153, 204, 255));
        buttonBeauties.setForeground(new java.awt.Color(51, 51, 51));
        buttonBeauties.setText("Beauties");
        buttonBeauties.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buttonBeauties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonBeautiesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonBeautiesMouseExited(evt);
            }
        });

        buttonBooks.setBackground(new java.awt.Color(153, 204, 255));
        buttonBooks.setText("Books");
        buttonBooks.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buttonBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonBooksMouseExited(evt);
            }
        });

        buttonClothing.setBackground(new java.awt.Color(153, 204, 255));
        buttonClothing.setText("Clothing");
        buttonClothing.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buttonClothing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonClothingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonClothingMouseExited(evt);
            }
        });
        buttonClothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClothingActionPerformed(evt);
            }
        });

        ButtonComputers.setBackground(new java.awt.Color(153, 204, 255));
        ButtonComputers.setText("Computers");
        ButtonComputers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        ButtonComputers.setBorderPainted(true);
        ButtonComputers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonComputersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonComputersMouseExited(evt);
            }
        });
        ButtonComputers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonComputersActionPerformed(evt);
            }
        });

        buttonElectronics.setBackground(new java.awt.Color(153, 204, 255));
        buttonElectronics.setText("Electronics");
        buttonElectronics.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buttonElectronics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonElectronicsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonElectronicsMouseExited(evt);
            }
        });

        buttonAll.setBackground(new java.awt.Color(153, 204, 255));
        buttonAll.setText("All");
        buttonAll.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buttonAll.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        buttonAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonAllMouseExited(evt);
            }
        });
        buttonAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanel3Layout = new javax.swing.GroupLayout(buttonPanel3);
        buttonPanel3.setLayout(buttonPanel3Layout);
        buttonPanel3Layout.setHorizontalGroup(
            buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonElectronics, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(ButtonComputers, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonClothing, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonBeauties, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonToys, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonSports, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanel3Layout.setVerticalGroup(
            buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonSports, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonToys, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBeauties, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonClothing, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonComputers, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonElectronics, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        wishlistIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/wishlist.png"))); // NOI18N
        wishlistIcon.setText("Wishlist");

        orderlistIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/list.png"))); // NOI18N
        orderlistIcon.setText("Orders");

        cartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shopping-cart.png"))); // NOI18N
        cartIcon.setText("Cart");

        searchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/search.png"))); // NOI18N

        searchField.setForeground(new java.awt.Color(153, 153, 153));
        searchField.setText("    Search for products ....");
        searchField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        searchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFieldFocusLost(evt);
            }
        });
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPanel2Layout = new javax.swing.GroupLayout(statusPanel2);
        statusPanel2.setLayout(statusPanel2Layout);
        statusPanel2Layout.setHorizontalGroup(
            statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(statusPanel2Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(searchIcon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cartIcon)
                .addGap(18, 18, 18)
                .addComponent(wishlistIcon)
                .addGap(18, 18, 18)
                .addComponent(orderlistIcon)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        statusPanel2Layout.setVerticalGroup(
            statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(statusPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(searchIcon))))
                    .addGroup(statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orderlistIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cartIcon)
                        .addComponent(wishlistIcon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(buttonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel25.setBackground(new java.awt.Color(204, 255, 255));
        jPanel25.setLayout(new java.awt.CardLayout());

        productPanel1.setBackground(new java.awt.Color(204, 204, 204));

        Product8MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        Product8MainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        product8Panel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout product8PanelLayout = new javax.swing.GroupLayout(product8Panel);
        product8Panel.setLayout(product8PanelLayout);
        product8PanelLayout.setHorizontalGroup(
            product8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product8PanelLayout.createSequentialGroup()
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        product8PanelLayout.setVerticalGroup(
            product8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product8PanelLayout.createSequentialGroup()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(product8PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        product8Description.setText("Black Tshirt Cotton Men");

        Product8price.setText("Rs. 800");

        product8rating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_529639780_Preview (1).png"))); // NOI18N

        product8BuyButoon.setBackground(new java.awt.Color(153, 204, 255));
        product8BuyButoon.setText("Buy");

        Product8AddtocarButton.setBackground(new java.awt.Color(204, 204, 204));
        Product8AddtocarButton.setText("Add To Cart");
        Product8AddtocarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product8AddtocarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Product8MainPanelLayout = new javax.swing.GroupLayout(Product8MainPanel);
        Product8MainPanel.setLayout(Product8MainPanelLayout);
        Product8MainPanelLayout.setHorizontalGroup(
            Product8MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(product8Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Product8MainPanelLayout.createSequentialGroup()
                .addGroup(Product8MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Product8MainPanelLayout.createSequentialGroup()
                        .addGroup(Product8MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Product8MainPanelLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(product8rating))
                            .addGroup(Product8MainPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(product8Description))
                            .addGroup(Product8MainPanelLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(Product8price)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Product8MainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Product8AddtocarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(product8BuyButoon)))
                .addContainerGap())
        );
        Product8MainPanelLayout.setVerticalGroup(
            Product8MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Product8MainPanelLayout.createSequentialGroup()
                .addComponent(product8Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product8rating)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product8Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Product8price)
                .addGap(18, 18, 18)
                .addGroup(Product8MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product8BuyButoon)
                    .addComponent(Product8AddtocarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Product7MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        Product7MainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        product7Panel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout product7PanelLayout = new javax.swing.GroupLayout(product7Panel);
        product7Panel.setLayout(product7PanelLayout);
        product7PanelLayout.setHorizontalGroup(
            product7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product7PanelLayout.createSequentialGroup()
                .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        product7PanelLayout.setVerticalGroup(
            product7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product7PanelLayout.createSequentialGroup()
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(product7PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        product7Description.setText("Black Tshirt Cotton Men");

        Product7price.setText("Rs. 800");

        product7rating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_669263419_Preview (1).png"))); // NOI18N

        product7BuyButoon.setBackground(new java.awt.Color(153, 204, 255));
        product7BuyButoon.setText("Buy");

        Product7AddtocarButton.setBackground(new java.awt.Color(204, 204, 204));
        Product7AddtocarButton.setText("Add To Cart");
        Product7AddtocarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product7AddtocarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Product7MainPanelLayout = new javax.swing.GroupLayout(Product7MainPanel);
        Product7MainPanel.setLayout(Product7MainPanelLayout);
        Product7MainPanelLayout.setHorizontalGroup(
            Product7MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(product7Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Product7MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(product7rating)
                .addGap(63, 63, 63))
            .addGroup(Product7MainPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(Product7price)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Product7MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Product7MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Product7MainPanelLayout.createSequentialGroup()
                        .addComponent(product7Description)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Product7MainPanelLayout.createSequentialGroup()
                        .addComponent(Product7AddtocarButton)
                        .addGap(18, 18, 18)
                        .addComponent(product7BuyButoon)
                        .addContainerGap())))
        );
        Product7MainPanelLayout.setVerticalGroup(
            Product7MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Product7MainPanelLayout.createSequentialGroup()
                .addComponent(product7Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product7rating, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product7Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Product7price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Product7MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(product7BuyButoon)
                    .addComponent(Product7AddtocarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Product6MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        Product6MainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        product6Panel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout product6PanelLayout = new javax.swing.GroupLayout(product6Panel);
        product6Panel.setLayout(product6PanelLayout);
        product6PanelLayout.setHorizontalGroup(
            product6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product6PanelLayout.createSequentialGroup()
                .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel53)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        product6PanelLayout.setVerticalGroup(
            product6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product6PanelLayout.createSequentialGroup()
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(product6PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel53)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        product6Description.setText("Black Tshirt Cotton Men");

        Product6price.setText("Rs. 800");

        product6rating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_529639780_Preview (1).png"))); // NOI18N

        product6BuyButoon.setBackground(new java.awt.Color(153, 204, 255));
        product6BuyButoon.setText("Buy");

        Product6AddtocarButton.setBackground(new java.awt.Color(204, 204, 204));
        Product6AddtocarButton.setText("Add To Cart");
        Product6AddtocarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product6AddtocarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Product6MainPanelLayout = new javax.swing.GroupLayout(Product6MainPanel);
        Product6MainPanel.setLayout(Product6MainPanelLayout);
        Product6MainPanelLayout.setHorizontalGroup(
            Product6MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(product6Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Product6MainPanelLayout.createSequentialGroup()
                .addGroup(Product6MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Product6MainPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(product6rating))
                    .addGroup(Product6MainPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(product6Description))
                    .addGroup(Product6MainPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(Product6price)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Product6MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Product6AddtocarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(product6BuyButoon)
                .addGap(15, 15, 15))
        );
        Product6MainPanelLayout.setVerticalGroup(
            Product6MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Product6MainPanelLayout.createSequentialGroup()
                .addComponent(product6Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product6rating)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product6Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Product6price)
                .addGap(18, 18, 18)
                .addGroup(Product6MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product6BuyButoon)
                    .addComponent(Product6AddtocarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Product5MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        Product5MainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        product5Panel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout product5PanelLayout = new javax.swing.GroupLayout(product5Panel);
        product5Panel.setLayout(product5PanelLayout);
        product5PanelLayout.setHorizontalGroup(
            product5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product5PanelLayout.createSequentialGroup()
                .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        product5PanelLayout.setVerticalGroup(
            product5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product5PanelLayout.createSequentialGroup()
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(product5PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel48)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        product5Description.setText("Black Tshirt Cotton Men");

        Product5price.setText("Rs. 800");

        product5rating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_669263419_Preview (1).png"))); // NOI18N

        Product5AddtocarButton.setBackground(new java.awt.Color(204, 204, 204));
        Product5AddtocarButton.setText("Add To Cart");
        Product5AddtocarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product5AddtocarButtonActionPerformed(evt);
            }
        });

        product5BuyButoon.setBackground(new java.awt.Color(153, 204, 255));
        product5BuyButoon.setText("Buy");

        javax.swing.GroupLayout Product5MainPanelLayout = new javax.swing.GroupLayout(Product5MainPanel);
        Product5MainPanel.setLayout(Product5MainPanelLayout);
        Product5MainPanelLayout.setHorizontalGroup(
            Product5MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(product5Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Product5MainPanelLayout.createSequentialGroup()
                .addGroup(Product5MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Product5MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Product5AddtocarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(product5BuyButoon))
                    .addGroup(Product5MainPanelLayout.createSequentialGroup()
                        .addGroup(Product5MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Product5MainPanelLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(Product5price))
                            .addGroup(Product5MainPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(product5rating))
                            .addGroup(Product5MainPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(product5Description)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Product5MainPanelLayout.setVerticalGroup(
            Product5MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Product5MainPanelLayout.createSequentialGroup()
                .addComponent(product5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product5rating, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product5Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Product5price)
                .addGap(18, 18, 18)
                .addGroup(Product5MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product5AddtocarButton)
                    .addComponent(product5BuyButoon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Product2MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        Product2MainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        product2Panel.setBackground(new java.awt.Color(204, 204, 204));

        product2pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout product2PanelLayout = new javax.swing.GroupLayout(product2Panel);
        product2Panel.setLayout(product2PanelLayout);
        product2PanelLayout.setHorizontalGroup(
            product2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product2PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(product2pic)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        product2PanelLayout.setVerticalGroup(
            product2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(product2pic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        product2Description.setText("Black Tshirt Cotton Men");

        product2price.setText("Rs. 800");

        product2rating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_669263419_Preview (1).png"))); // NOI18N

        Product2AddtocarButton.setBackground(new java.awt.Color(204, 204, 204));
        Product2AddtocarButton.setText("Add To Cart");
        Product2AddtocarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product2AddtocarButtonActionPerformed(evt);
            }
        });

        product2BuyButoon.setBackground(new java.awt.Color(153, 204, 255));
        product2BuyButoon.setText("Buy");

        javax.swing.GroupLayout Product2MainPanelLayout = new javax.swing.GroupLayout(Product2MainPanel);
        Product2MainPanel.setLayout(Product2MainPanelLayout);
        Product2MainPanelLayout.setHorizontalGroup(
            Product2MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(product2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Product2MainPanelLayout.createSequentialGroup()
                .addGroup(Product2MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Product2MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Product2AddtocarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(product2BuyButoon))
                    .addGroup(Product2MainPanelLayout.createSequentialGroup()
                        .addGroup(Product2MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Product2MainPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(product2rating))
                            .addGroup(Product2MainPanelLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(product2price))
                            .addGroup(Product2MainPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(product2Description)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Product2MainPanelLayout.setVerticalGroup(
            Product2MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Product2MainPanelLayout.createSequentialGroup()
                .addComponent(product2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product2rating, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product2Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product2price, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Product2MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product2AddtocarButton)
                    .addComponent(product2BuyButoon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Product4MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        Product4MainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        product4Panel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout product4PanelLayout = new javax.swing.GroupLayout(product4Panel);
        product4Panel.setLayout(product4PanelLayout);
        product4PanelLayout.setHorizontalGroup(
            product4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product4PanelLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        product4PanelLayout.setVerticalGroup(
            product4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product4PanelLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(product4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        product4Description.setText("Black Tshirt Cotton Men");

        Product4price.setText("Rs. 800");

        product4rating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_669263419_Preview (1).png"))); // NOI18N

        Product4AddtocarButton.setBackground(new java.awt.Color(204, 204, 204));
        Product4AddtocarButton.setText("Add To Cart");
        Product4AddtocarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product4AddtocarButtonActionPerformed(evt);
            }
        });

        product4BuyButoon.setBackground(new java.awt.Color(153, 204, 255));
        product4BuyButoon.setText("Buy");

        javax.swing.GroupLayout Product4MainPanelLayout = new javax.swing.GroupLayout(Product4MainPanel);
        Product4MainPanel.setLayout(Product4MainPanelLayout);
        Product4MainPanelLayout.setHorizontalGroup(
            Product4MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(product4Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Product4MainPanelLayout.createSequentialGroup()
                .addGroup(Product4MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Product4MainPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(product4rating))
                    .addGroup(Product4MainPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(product4Description))
                    .addGroup(Product4MainPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Product4price))
                    .addGroup(Product4MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Product4AddtocarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(product4BuyButoon)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        Product4MainPanelLayout.setVerticalGroup(
            Product4MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Product4MainPanelLayout.createSequentialGroup()
                .addComponent(product4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product4rating, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product4Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Product4price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Product4MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product4AddtocarButton)
                    .addComponent(product4BuyButoon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Product3MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        Product3MainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        Product3Panel.setBackground(new java.awt.Color(204, 204, 204));

        product3pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout Product3PanelLayout = new javax.swing.GroupLayout(Product3Panel);
        Product3Panel.setLayout(Product3PanelLayout);
        Product3PanelLayout.setHorizontalGroup(
            Product3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Product3PanelLayout.createSequentialGroup()
                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product3pic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Product3PanelLayout.setVerticalGroup(
            Product3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Product3PanelLayout.createSequentialGroup()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Product3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(product3pic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        product3Description.setText("Black Tshirt Cotton Men");

        Product3price.setText("Rs. 800");

        product3rating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_529639780_Preview (1).png"))); // NOI18N

        Product3AddtocarButton.setBackground(new java.awt.Color(204, 204, 204));
        Product3AddtocarButton.setText("Add To Cart");
        Product3AddtocarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product3AddtocarButtonActionPerformed(evt);
            }
        });

        product3BuyButoon.setBackground(new java.awt.Color(153, 204, 255));
        product3BuyButoon.setText("Buy");

        javax.swing.GroupLayout Product3MainPanelLayout = new javax.swing.GroupLayout(Product3MainPanel);
        Product3MainPanel.setLayout(Product3MainPanelLayout);
        Product3MainPanelLayout.setHorizontalGroup(
            Product3MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Product3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Product3MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Product3AddtocarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(product3BuyButoon)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Product3MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(product3rating)
                .addGap(61, 61, 61))
            .addGroup(Product3MainPanelLayout.createSequentialGroup()
                .addGroup(Product3MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Product3MainPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(product3Description))
                    .addGroup(Product3MainPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(Product3price)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Product3MainPanelLayout.setVerticalGroup(
            Product3MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Product3MainPanelLayout.createSequentialGroup()
                .addComponent(Product3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product3rating)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product3Description, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Product3price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Product3MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product3AddtocarButton)
                    .addComponent(product3BuyButoon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Product1MainPanel1.setBackground(new java.awt.Color(255, 255, 255));
        Product1MainPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        product1Panel1.setBackground(new java.awt.Color(204, 204, 204));

        product2pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout product1Panel1Layout = new javax.swing.GroupLayout(product1Panel1);
        product1Panel1.setLayout(product1Panel1Layout);
        product1Panel1Layout.setHorizontalGroup(
            product1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product1Panel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(product2pic1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        product1Panel1Layout.setVerticalGroup(
            product1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product1Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(product2pic1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        product1Description.setText("Black Tshirt Cotton Men");

        Product1price.setText("Rs. 800");

        product1rating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_529639780_Preview (1).png"))); // NOI18N

        Product1AddtocarButton.setBackground(new java.awt.Color(204, 204, 204));
        Product1AddtocarButton.setText("Add To Cart");
        Product1AddtocarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product1AddtocarButtonActionPerformed(evt);
            }
        });

        product1BuyButoon.setBackground(new java.awt.Color(153, 204, 255));
        product1BuyButoon.setText("Buy");

        javax.swing.GroupLayout Product1MainPanel1Layout = new javax.swing.GroupLayout(Product1MainPanel1);
        Product1MainPanel1.setLayout(Product1MainPanel1Layout);
        Product1MainPanel1Layout.setHorizontalGroup(
            Product1MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(product1Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Product1MainPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(product1rating)
                .addGap(57, 57, 57))
            .addGroup(Product1MainPanel1Layout.createSequentialGroup()
                .addGroup(Product1MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Product1MainPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(product1Description))
                    .addGroup(Product1MainPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Product1price))
                    .addGroup(Product1MainPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Product1AddtocarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(product1BuyButoon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Product1MainPanel1Layout.setVerticalGroup(
            Product1MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Product1MainPanel1Layout.createSequentialGroup()
                .addComponent(product1Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product1rating)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product1Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Product1price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Product1MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product1AddtocarButton)
                    .addComponent(product1BuyButoon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightclickPanel1.setBackground(new java.awt.Color(204, 204, 204,0));

        rightclickIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/right-arrow.png"))); // NOI18N

        javax.swing.GroupLayout rightclickPanel1Layout = new javax.swing.GroupLayout(rightclickPanel1);
        rightclickPanel1.setLayout(rightclickPanel1Layout);
        rightclickPanel1Layout.setHorizontalGroup(
            rightclickPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightclickPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rightclickIcon)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        rightclickPanel1Layout.setVerticalGroup(
            rightclickPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightclickPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(rightclickIcon)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout productPanel1Layout = new javax.swing.GroupLayout(productPanel1);
        productPanel1.setLayout(productPanel1Layout);
        productPanel1Layout.setHorizontalGroup(
            productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Product1MainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product5MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Product2MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product6MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Product7MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Product3MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Product8MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Product4MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addComponent(rightclickPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        productPanel1Layout.setVerticalGroup(
            productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productPanel1Layout.createSequentialGroup()
                        .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Product3MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Product4MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Product7MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Product8MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanel1Layout.createSequentialGroup()
                        .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Product2MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Product1MainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Product6MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Product5MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(productPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(rightclickPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoutPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(statusPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAllActionPerformed

    private void ButtonComputersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonComputersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonComputersActionPerformed

    private void buttonSportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSportsActionPerformed

    private void buttonClothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClothingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClothingActionPerformed

    private void buttonElectronicsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonElectronicsMouseEntered
        buttonElectronics.setBackground(new Color(51,204,255 ));
         // semi-transparent background
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonElectronicsMouseEntered

    private void buttonElectronicsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonElectronicsMouseExited
        buttonElectronics.setBackground(new Color(153,204,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonElectronicsMouseExited

    private void buttonAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAllMouseEntered
        buttonAll.setBackground(new Color (51, 204, 255));                // TODO add your handling code here:
    }//GEN-LAST:event_buttonAllMouseEntered

    private void buttonAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAllMouseExited
        buttonAll.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAllMouseExited

    private void ButtonComputersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonComputersMouseEntered
        ButtonComputers.setBackground(new Color(51,204,255));      // TODO add your handling code here:
    }//GEN-LAST:event_ButtonComputersMouseEntered

    private void ButtonComputersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonComputersMouseExited
        ButtonComputers.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonComputersMouseExited

    private void buttonClothingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClothingMouseEntered
        buttonClothing.setBackground(new Color(51,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClothingMouseEntered

    private void buttonClothingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClothingMouseExited
        buttonClothing.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClothingMouseExited

    private void buttonBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBooksMouseEntered
        buttonBooks.setBackground(new Color(51,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBooksMouseEntered

    private void buttonBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBooksMouseExited
        buttonBooks.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBooksMouseExited

    private void buttonBeautiesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBeautiesMouseEntered
        buttonBeauties.setBackground(new Color(51,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBeautiesMouseEntered

    private void buttonBeautiesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBeautiesMouseExited
        buttonBeauties.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBeautiesMouseExited

    private void buttonToysMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonToysMouseEntered
        buttonToys.setBackground(new Color(51,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonToysMouseEntered

    private void buttonToysMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonToysMouseExited
        buttonToys.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonToysMouseExited

    private void buttonSportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSportsMouseEntered
        buttonSports.setBackground(new Color(51,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSportsMouseEntered

    private void buttonSportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSportsMouseExited
        buttonSports.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSportsMouseExited

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusGained
        if (searchField.getText().equals("    Search for products ....")) {
        searchField.setText("    ");
        searchField.setForeground(Color.BLACK);
      }
    }//GEN-LAST:event_searchFieldFocusGained

    private void searchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusLost
        if (searchField.getText().trim().isEmpty()) {
        searchField.setText("    Search for products ....");
        searchField.setForeground(Color.GRAY);
      }
    }//GEN-LAST:event_searchFieldFocusLost

    private void Product1AddtocarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product1AddtocarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product1AddtocarButtonActionPerformed

    private void Product2AddtocarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product2AddtocarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product2AddtocarButtonActionPerformed

    private void Product3AddtocarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product3AddtocarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product3AddtocarButtonActionPerformed

    private void Product4AddtocarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product4AddtocarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product4AddtocarButtonActionPerformed

    private void Product8AddtocarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product8AddtocarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product8AddtocarButtonActionPerformed

    private void Product7AddtocarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product7AddtocarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product7AddtocarButtonActionPerformed

    private void Product6AddtocarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product6AddtocarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product6AddtocarButtonActionPerformed

    private void Product5AddtocarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product5AddtocarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product5AddtocarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonComputers;
    private javax.swing.JButton Product1AddtocarButton;
    private javax.swing.JPanel Product1MainPanel1;
    private javax.swing.JLabel Product1price;
    private javax.swing.JButton Product2AddtocarButton;
    private javax.swing.JPanel Product2MainPanel;
    private javax.swing.JButton Product3AddtocarButton;
    private javax.swing.JPanel Product3MainPanel;
    private javax.swing.JPanel Product3Panel;
    private javax.swing.JLabel Product3price;
    private javax.swing.JButton Product4AddtocarButton;
    private javax.swing.JPanel Product4MainPanel;
    private javax.swing.JLabel Product4price;
    private javax.swing.JButton Product5AddtocarButton;
    private javax.swing.JPanel Product5MainPanel;
    private javax.swing.JLabel Product5price;
    private javax.swing.JButton Product6AddtocarButton;
    private javax.swing.JPanel Product6MainPanel;
    private javax.swing.JLabel Product6price;
    private javax.swing.JButton Product7AddtocarButton;
    private javax.swing.JPanel Product7MainPanel;
    private javax.swing.JLabel Product7price;
    private javax.swing.JButton Product8AddtocarButton;
    private javax.swing.JPanel Product8MainPanel;
    private javax.swing.JLabel Product8price;
    private javax.swing.JButton buttonAll;
    private javax.swing.JButton buttonBeauties;
    private javax.swing.JButton buttonBooks;
    private javax.swing.JButton buttonClothing;
    private javax.swing.JButton buttonElectronics;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JPanel buttonPanel3;
    private javax.swing.JButton buttonSports;
    private javax.swing.JButton buttonToys;
    private javax.swing.JLabel cartIcon;
    private javax.swing.JLabel dashboardLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel logoutPanel1;
    private javax.swing.JLabel orderlistIcon;
    private javax.swing.JButton product1BuyButoon;
    private javax.swing.JLabel product1Description;
    private javax.swing.JPanel product1Panel1;
    private javax.swing.JLabel product1rating;
    private javax.swing.JButton product2BuyButoon;
    private javax.swing.JLabel product2Description;
    private javax.swing.JPanel product2Panel;
    private javax.swing.JLabel product2pic;
    private javax.swing.JLabel product2pic1;
    private javax.swing.JLabel product2price;
    private javax.swing.JLabel product2rating;
    private javax.swing.JButton product3BuyButoon;
    private javax.swing.JLabel product3Description;
    private javax.swing.JLabel product3pic;
    private javax.swing.JLabel product3rating;
    private javax.swing.JButton product4BuyButoon;
    private javax.swing.JLabel product4Description;
    private javax.swing.JPanel product4Panel;
    private javax.swing.JLabel product4rating;
    private javax.swing.JButton product5BuyButoon;
    private javax.swing.JLabel product5Description;
    private javax.swing.JPanel product5Panel;
    private javax.swing.JLabel product5rating;
    private javax.swing.JButton product6BuyButoon;
    private javax.swing.JLabel product6Description;
    private javax.swing.JPanel product6Panel;
    private javax.swing.JLabel product6rating;
    private javax.swing.JButton product7BuyButoon;
    private javax.swing.JLabel product7Description;
    private javax.swing.JPanel product7Panel;
    private javax.swing.JLabel product7rating;
    private javax.swing.JButton product8BuyButoon;
    private javax.swing.JLabel product8Description;
    private javax.swing.JPanel product8Panel;
    private javax.swing.JLabel product8rating;
    private javax.swing.JPanel productPanel1;
    private javax.swing.JLabel rightclickIcon;
    private javax.swing.JPanel rightclickPanel1;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JPanel statusPanel2;
    private javax.swing.JLabel wishlistIcon;
    // End of variables declaration//GEN-END:variables
}
