/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buysmart.view;

import java.awt.Color;

import javax.swing.JFrame;



/**
 *
 * @author fahmi
 */
public class Dashboard extends javax.swing.JFrame {
    

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        logoutPanel1 = new javax.swing.JPanel();
        buttonLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dashboardLogo = new javax.swing.JLabel();
        statusPanel2 = new javax.swing.JPanel();
        buttonPanel3 = new javax.swing.JPanel();
        buttonSports = new javax.swing.JButton();
        buttonToys = new javax.swing.JButton();
        buttonBeauties = new javax.swing.JButton();
        buttonBooks = new javax.swing.JButton();
        buttonClothing = new javax.swing.JButton();
        ButtonComputers = new javax.swing.JButton();
        buttonElectronics = new javax.swing.JButton();
        buttonAll = new javax.swing.JButton();
        wishlistIcon = new javax.swing.JLabel();
        orderlistIcon = new javax.swing.JLabel();
        cartIcon = new javax.swing.JLabel();
        searchIcon = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        productPanel1 = new javax.swing.JPanel();
        PanelProductCard = new javax.swing.JPanel();
        PicProduct = new javax.swing.JLabel();
        ProductAddToCartButton = new javax.swing.JButton();
        ProductCardPrice = new javax.swing.JLabel();
        DescriptionProductCard = new javax.swing.JLabel();
        PanelProductCard1 = new javax.swing.JPanel();
        PicProduct1 = new javax.swing.JLabel();
        ProductAddToCartButton1 = new javax.swing.JButton();
        ProductCardPrice1 = new javax.swing.JLabel();
        DescriptionProductCard1 = new javax.swing.JLabel();
        PanelProductCard2 = new javax.swing.JPanel();
        PicProduct2 = new javax.swing.JLabel();
        ProductAddToCartButton2 = new javax.swing.JButton();
        ProductCardPrice2 = new javax.swing.JLabel();
        DescriptionProductCard2 = new javax.swing.JLabel();
        PanelProductCard3 = new javax.swing.JPanel();
        PicProduct3 = new javax.swing.JLabel();
        ProductAddToCartButton3 = new javax.swing.JButton();
        ProductCardPrice3 = new javax.swing.JLabel();
        DescriptionProductCard3 = new javax.swing.JLabel();
        PanelProductCard4 = new javax.swing.JPanel();
        PicProduct4 = new javax.swing.JLabel();
        ProductAddToCartButton4 = new javax.swing.JButton();
        ProductCardPrice4 = new javax.swing.JLabel();
        DescriptionProductCard4 = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setText("Black Tshirt Cotton Men");

        jLabel16.setText("Rs. 800");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_529639780_Preview (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel17)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shirt (1) copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel25.setText("Black Tshirt Cotton Men");

        jLabel26.setText("Rs. 800");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/AdobeStock_529639780_Preview (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel26))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel25))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel27)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(15, 15, 15)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        logoutPanel1.setBackground(new java.awt.Color(204, 204, 204));

        buttonLogout.setBackground(new java.awt.Color(153, 204, 255));
        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/user (1).png"))); // NOI18N

        dashboardLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/logo40.png"))); // NOI18N

        javax.swing.GroupLayout logoutPanel1Layout = new javax.swing.GroupLayout(logoutPanel1);
        logoutPanel1.setLayout(logoutPanel1Layout);
        logoutPanel1Layout.setHorizontalGroup(
            logoutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(dashboardLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(50, 50, 50))
        );
        logoutPanel1Layout.setVerticalGroup(
            logoutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(logoutPanel1Layout.createSequentialGroup()
                        .addComponent(dashboardLogo)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(logoutPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buttonPanel3.setBackground(new java.awt.Color(51, 153, 255));

        buttonSports.setBackground(new java.awt.Color(153, 204, 255));
        buttonSports.setText("Sports");
        buttonSports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSportsMouseExited(evt);
            }
        });
        buttonSports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSportsActionPerformed(evt);
            }
        });

        buttonToys.setBackground(new java.awt.Color(153, 204, 255));
        buttonToys.setText("Toys");
        buttonToys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonToysMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonToysMouseExited(evt);
            }
        });

        buttonBeauties.setBackground(new java.awt.Color(153, 204, 255));
        buttonBeauties.setForeground(new java.awt.Color(51, 51, 51));
        buttonBeauties.setText("Beauties");
        buttonBeauties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonBeautiesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonBeautiesMouseExited(evt);
            }
        });

        buttonBooks.setBackground(new java.awt.Color(153, 204, 255));
        buttonBooks.setText("Books");
        buttonBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonBooksMouseExited(evt);
            }
        });

        buttonClothing.setBackground(new java.awt.Color(153, 204, 255));
        buttonClothing.setText("Clothing");
        buttonClothing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonClothingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonClothingMouseExited(evt);
            }
        });
        buttonClothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClothingActionPerformed(evt);
            }
        });

        ButtonComputers.setBackground(new java.awt.Color(153, 204, 255));
        ButtonComputers.setText("Computers");
        ButtonComputers.setBorderPainted(true);
        ButtonComputers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonComputersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonComputersMouseExited(evt);
            }
        });
        ButtonComputers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonComputersActionPerformed(evt);
            }
        });

        buttonElectronics.setBackground(new java.awt.Color(153, 204, 255));
        buttonElectronics.setText("Electronics");
        buttonElectronics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonElectronicsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonElectronicsMouseExited(evt);
            }
        });

        buttonAll.setBackground(new java.awt.Color(153, 204, 255));
        buttonAll.setText("All");
        buttonAll.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        buttonAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonAllMouseExited(evt);
            }
        });
        buttonAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanel3Layout = new javax.swing.GroupLayout(buttonPanel3);
        buttonPanel3.setLayout(buttonPanel3Layout);
        buttonPanel3Layout.setHorizontalGroup(
            buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonElectronics, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(ButtonComputers, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonClothing, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonBeauties, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonToys, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonSports, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanel3Layout.setVerticalGroup(
            buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonSports, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonToys, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBeauties, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonClothing, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonComputers, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonElectronics, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        wishlistIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/wishlist.png"))); // NOI18N
        wishlistIcon.setText("Wishlist");

        orderlistIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/list.png"))); // NOI18N
        orderlistIcon.setText("Orders");

        cartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/shopping-cart.png"))); // NOI18N
        cartIcon.setText("Cart");

        searchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/search.png"))); // NOI18N

        searchField.setForeground(new java.awt.Color(153, 153, 153));
        searchField.setText("    Search for products ....");
        searchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFieldFocusLost(evt);
            }
        });
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPanel2Layout = new javax.swing.GroupLayout(statusPanel2);
        statusPanel2.setLayout(statusPanel2Layout);
        statusPanel2Layout.setHorizontalGroup(
            statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(statusPanel2Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(searchIcon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cartIcon)
                .addGap(18, 18, 18)
                .addComponent(wishlistIcon)
                .addGap(18, 18, 18)
                .addComponent(orderlistIcon)
                .addGap(18, 18, 18))
            .addGroup(statusPanel2Layout.createSequentialGroup()
                .addComponent(buttonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        statusPanel2Layout.setVerticalGroup(
            statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(statusPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(searchIcon))))
                    .addGroup(statusPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orderlistIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cartIcon)
                        .addComponent(wishlistIcon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(buttonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel25.setBackground(new java.awt.Color(204, 255, 255));
        jPanel25.setLayout(new java.awt.CardLayout());

        productPanel1.setBackground(new java.awt.Color(204, 204, 204));

        PicProduct.setText("pic");
        PicProduct.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductAddToCartButton.setBackground(new java.awt.Color(153, 204, 255));
        ProductAddToCartButton.setText("Add To Card");

        ProductCardPrice.setBackground(new java.awt.Color(255, 255, 255));
        ProductCardPrice.setText("jLabel2");

        DescriptionProductCard.setText("jLabel2");

        javax.swing.GroupLayout PanelProductCardLayout = new javax.swing.GroupLayout(PanelProductCard);
        PanelProductCard.setLayout(PanelProductCardLayout);
        PanelProductCardLayout.setHorizontalGroup(
            PanelProductCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PicProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProductCardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelProductCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DescriptionProductCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelProductCardLayout.createSequentialGroup()
                        .addComponent(ProductCardPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(ProductAddToCartButton)))
                .addGap(16, 16, 16))
        );
        PanelProductCardLayout.setVerticalGroup(
            PanelProductCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductCardLayout.createSequentialGroup()
                .addComponent(PicProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriptionProductCard, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelProductCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductAddToCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductCardPrice))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        PicProduct1.setText("pic");
        PicProduct1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductAddToCartButton1.setBackground(new java.awt.Color(153, 204, 255));
        ProductAddToCartButton1.setText("Add To Cart");

        ProductCardPrice1.setBackground(new java.awt.Color(255, 255, 255));
        ProductCardPrice1.setText("jLabel2");

        DescriptionProductCard1.setText("jLabel2");

        javax.swing.GroupLayout PanelProductCard1Layout = new javax.swing.GroupLayout(PanelProductCard1);
        PanelProductCard1.setLayout(PanelProductCard1Layout);
        PanelProductCard1Layout.setHorizontalGroup(
            PanelProductCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PicProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProductCard1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelProductCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelProductCard1Layout.createSequentialGroup()
                        .addComponent(ProductCardPrice1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(ProductAddToCartButton1))
                    .addComponent(DescriptionProductCard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        PanelProductCard1Layout.setVerticalGroup(
            PanelProductCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductCard1Layout.createSequentialGroup()
                .addComponent(PicProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriptionProductCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelProductCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductAddToCartButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductCardPrice1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PicProduct2.setText("pic");
        PicProduct2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductAddToCartButton2.setBackground(new java.awt.Color(153, 204, 255));
        ProductAddToCartButton2.setText("Add To Cart");

        ProductCardPrice2.setBackground(new java.awt.Color(255, 255, 255));
        ProductCardPrice2.setText("jLabel2");

        DescriptionProductCard2.setText("jLabel2");

        javax.swing.GroupLayout PanelProductCard2Layout = new javax.swing.GroupLayout(PanelProductCard2);
        PanelProductCard2.setLayout(PanelProductCard2Layout);
        PanelProductCard2Layout.setHorizontalGroup(
            PanelProductCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PicProduct2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProductCard2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelProductCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DescriptionProductCard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelProductCard2Layout.createSequentialGroup()
                        .addComponent(ProductCardPrice2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(ProductAddToCartButton2)))
                .addGap(16, 16, 16))
        );
        PanelProductCard2Layout.setVerticalGroup(
            PanelProductCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductCard2Layout.createSequentialGroup()
                .addComponent(PicProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriptionProductCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelProductCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductAddToCartButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductCardPrice2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PicProduct3.setText("pic");
        PicProduct3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductAddToCartButton3.setBackground(new java.awt.Color(153, 204, 255));
        ProductAddToCartButton3.setText("Add To Cart");

        ProductCardPrice3.setBackground(new java.awt.Color(255, 255, 255));
        ProductCardPrice3.setText("jLabel2");

        DescriptionProductCard3.setText("jLabel2");

        javax.swing.GroupLayout PanelProductCard3Layout = new javax.swing.GroupLayout(PanelProductCard3);
        PanelProductCard3.setLayout(PanelProductCard3Layout);
        PanelProductCard3Layout.setHorizontalGroup(
            PanelProductCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProductCard3Layout.createSequentialGroup()
                .addGroup(PanelProductCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelProductCard3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DescriptionProductCard3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelProductCard3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(ProductCardPrice3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(ProductAddToCartButton3)))
                .addGap(16, 16, 16))
            .addComponent(PicProduct3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelProductCard3Layout.setVerticalGroup(
            PanelProductCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductCard3Layout.createSequentialGroup()
                .addComponent(PicProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriptionProductCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(PanelProductCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductCardPrice3)
                    .addComponent(ProductAddToCartButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        PicProduct4.setText("pic");
        PicProduct4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductAddToCartButton4.setBackground(new java.awt.Color(153, 204, 255));
        ProductAddToCartButton4.setText("Add To Cart");

        ProductCardPrice4.setBackground(new java.awt.Color(255, 255, 255));
        ProductCardPrice4.setText("jLabel2");

        DescriptionProductCard4.setText("jLabel2");

        javax.swing.GroupLayout PanelProductCard4Layout = new javax.swing.GroupLayout(PanelProductCard4);
        PanelProductCard4.setLayout(PanelProductCard4Layout);
        PanelProductCard4Layout.setHorizontalGroup(
            PanelProductCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PicProduct4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelProductCard4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelProductCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescriptionProductCard4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelProductCard4Layout.createSequentialGroup()
                        .addComponent(ProductCardPrice4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(ProductAddToCartButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        PanelProductCard4Layout.setVerticalGroup(
            PanelProductCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductCard4Layout.createSequentialGroup()
                .addComponent(PicProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriptionProductCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelProductCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductAddToCartButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductCardPrice4))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout productPanel1Layout = new javax.swing.GroupLayout(productPanel1);
        productPanel1.setLayout(productPanel1Layout);
        productPanel1Layout.setHorizontalGroup(
            productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelProductCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(productPanel1Layout.createSequentialGroup()
                        .addComponent(PanelProductCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(PanelProductCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(PanelProductCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelProductCard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        productPanel1Layout.setVerticalGroup(
            productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelProductCard3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelProductCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelProductCard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelProductCard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelProductCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logoutPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoutPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 24, Short.MAX_VALUE)
                .addComponent(statusPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(productPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAllActionPerformed

    private void ButtonComputersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonComputersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonComputersActionPerformed

    private void buttonSportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSportsActionPerformed

    private void buttonClothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClothingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClothingActionPerformed

    private void buttonElectronicsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonElectronicsMouseEntered
        buttonElectronics.setBackground(new Color(51,204,255 ));
         // semi-transparent background
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonElectronicsMouseEntered

    private void buttonElectronicsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonElectronicsMouseExited
        buttonElectronics.setBackground(new Color(153,204,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonElectronicsMouseExited

    private void buttonAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAllMouseEntered
        buttonAll.setBackground(new Color (51, 204, 255));                // TODO add your handling code here:
    }//GEN-LAST:event_buttonAllMouseEntered

    private void buttonAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAllMouseExited
        buttonAll.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAllMouseExited

    private void ButtonComputersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonComputersMouseEntered
        ButtonComputers.setBackground(new Color(51,204,255));      // TODO add your handling code here:
    }//GEN-LAST:event_ButtonComputersMouseEntered

    private void ButtonComputersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonComputersMouseExited
        ButtonComputers.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonComputersMouseExited

    private void buttonClothingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClothingMouseEntered
        buttonClothing.setBackground(new Color(51,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClothingMouseEntered

    private void buttonClothingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClothingMouseExited
        buttonClothing.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClothingMouseExited

    private void buttonBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBooksMouseEntered
        buttonBooks.setBackground(new Color(51,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBooksMouseEntered

    private void buttonBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBooksMouseExited
        buttonBooks.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBooksMouseExited

    private void buttonBeautiesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBeautiesMouseEntered
        buttonBeauties.setBackground(new Color(51,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBeautiesMouseEntered

    private void buttonBeautiesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBeautiesMouseExited
        buttonBeauties.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBeautiesMouseExited

    private void buttonToysMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonToysMouseEntered
        buttonToys.setBackground(new Color(51,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonToysMouseEntered

    private void buttonToysMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonToysMouseExited
        buttonToys.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonToysMouseExited

    private void buttonSportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSportsMouseEntered
        buttonSports.setBackground(new Color(51,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSportsMouseEntered

    private void buttonSportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSportsMouseExited
        buttonSports.setBackground(new Color(153,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSportsMouseExited

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusGained
        if (searchField.getText().equals("    Search for products ....")) {
        searchField.setText("    ");
        searchField.setForeground(Color.BLACK);
      }
    }//GEN-LAST:event_searchFieldFocusGained

    private void searchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusLost
        if (searchField.getText().trim().isEmpty()) {
        searchField.setText("    Search for products ....");
        searchField.setForeground(Color.GRAY);
      }
    }//GEN-LAST:event_searchFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonComputers;
    private javax.swing.JLabel DescriptionProductCard;
    private javax.swing.JLabel DescriptionProductCard1;
    private javax.swing.JLabel DescriptionProductCard2;
    private javax.swing.JLabel DescriptionProductCard3;
    private javax.swing.JLabel DescriptionProductCard4;
    private javax.swing.JPanel PanelProductCard;
    private javax.swing.JPanel PanelProductCard1;
    private javax.swing.JPanel PanelProductCard2;
    private javax.swing.JPanel PanelProductCard3;
    private javax.swing.JPanel PanelProductCard4;
    private javax.swing.JLabel PicProduct;
    private javax.swing.JLabel PicProduct1;
    private javax.swing.JLabel PicProduct2;
    private javax.swing.JLabel PicProduct3;
    private javax.swing.JLabel PicProduct4;
    private javax.swing.JButton ProductAddToCartButton;
    private javax.swing.JButton ProductAddToCartButton1;
    private javax.swing.JButton ProductAddToCartButton2;
    private javax.swing.JButton ProductAddToCartButton3;
    private javax.swing.JButton ProductAddToCartButton4;
    private javax.swing.JLabel ProductCardPrice;
    private javax.swing.JLabel ProductCardPrice1;
    private javax.swing.JLabel ProductCardPrice2;
    private javax.swing.JLabel ProductCardPrice3;
    private javax.swing.JLabel ProductCardPrice4;
    private javax.swing.JButton buttonAll;
    private javax.swing.JButton buttonBeauties;
    private javax.swing.JButton buttonBooks;
    private javax.swing.JButton buttonClothing;
    private javax.swing.JButton buttonElectronics;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JPanel buttonPanel3;
    private javax.swing.JButton buttonSports;
    private javax.swing.JButton buttonToys;
    private javax.swing.JLabel cartIcon;
    private javax.swing.JLabel dashboardLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel logoutPanel1;
    private javax.swing.JLabel orderlistIcon;
    private javax.swing.JPanel productPanel1;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JPanel statusPanel2;
    private javax.swing.JLabel wishlistIcon;
    // End of variables declaration//GEN-END:variables

    
    
    
    
}
