/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buysmart.view;

import java.awt.event.ActionListener;
import javax.swing.JFrame;






/**
 *
 * @author batas
 */
public class ForgetPasswordView extends javax.swing.JFrame {

    /**
     */
    public ForgetPasswordView() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ResetEmail = new javax.swing.JPanel();
        EmailBox = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        CPasswordBox = new javax.swing.JPasswordField();
        NewPassword = new javax.swing.JLabel();
        NewPasswordBox = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JLabel();
        Confirm = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        SecurityQuestion = new javax.swing.JLabel();
        SecurityBox = new javax.swing.JComboBox<>();
        SecurityAnswerBox = new javax.swing.JTextField();
        SecurityAnswer = new javax.swing.JLabel();
        NpasswordCheckBox = new javax.swing.JCheckBox();
        CpasswordcheckBox = new javax.swing.JCheckBox();
        otpButton = new javax.swing.JButton();
        otpBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ClickButton = new javax.swing.JButton();
        ResetPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" BuySmart-ForgetPassword Page");
        

        jPanel1.setBackground(new java.awt.Color(255, 229, 209));

        ResetEmail.setBackground(new java.awt.Color(230, 255, 250));
        ResetEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ResetEmail.setPreferredSize(new java.awt.Dimension(603, 360));

        Email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Email.setText("Email");

        CPasswordBox.setEnabled(false);
        CPasswordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPasswordBoxActionPerformed(evt);
            }
        });

        NewPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NewPassword.setText("New Password");

        NewPasswordBox.setEnabled(false);

        ConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ConfirmPassword.setText("Confirm Password");

        Confirm.setBackground(new java.awt.Color(51, 255, 153));
        Confirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Confirm.setText("Confirm");
        Confirm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Confirm.setEnabled(false);

        Back.setBackground(new java.awt.Color(51, 255, 153));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setText("Back ");
        Back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        SecurityQuestion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SecurityQuestion.setText("Secuity Question");

        SecurityBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is my nickname ?", "What is my favorite color ?", "When is my birthday ?" }));
        SecurityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecurityBoxActionPerformed(evt);
            }
        });

        SecurityAnswer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SecurityAnswer.setText("Security Answer");

        NpasswordCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NpasswordCheckBox.setText("Show");

        CpasswordcheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CpasswordcheckBox.setText("Show");

        otpButton.setBackground(new java.awt.Color(51, 255, 153));
        otpButton.setText("Send OTP");
        otpButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        otpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpButtonActionPerformed(evt);
            }
        });

        otpBox.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("OTP");

        ClickButton.setBackground(new java.awt.Color(51, 255, 153));
        ClickButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ClickButton.setText("Click");
        ClickButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ClickButton.setEnabled(false);

        javax.swing.GroupLayout ResetEmailLayout = new javax.swing.GroupLayout(ResetEmail);
        ResetEmail.setLayout(ResetEmailLayout);
        ResetEmailLayout.setHorizontalGroup(
            ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResetEmailLayout.createSequentialGroup()
                .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResetEmailLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ResetEmailLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ResetEmailLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NewPassword)
                                    .addComponent(SecurityAnswer))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NewPasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(NpasswordCheckBox))
                            .addGroup(ResetEmailLayout.createSequentialGroup()
                                .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ResetEmailLayout.createSequentialGroup()
                                        .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SecurityQuestion)
                                            .addComponent(Email))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResetEmailLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(38, 38, 38)))
                                .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SecurityAnswerBox, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SecurityBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 178, Short.MAX_VALUE)
                                    .addComponent(otpBox, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EmailBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(otpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(ResetEmailLayout.createSequentialGroup()
                                        .addComponent(ClickButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(ResetEmailLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ConfirmPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CPasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CpasswordcheckBox)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        ResetEmailLayout.setVerticalGroup(
            ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResetEmailLayout.createSequentialGroup()
                .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ResetEmailLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(EmailBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SecurityQuestion)
                    .addComponent(SecurityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SecurityAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(otpButton)
                    .addComponent(SecurityAnswerBox, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResetEmailLayout.createSequentialGroup()
                        .addComponent(ClickButton)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResetEmailLayout.createSequentialGroup()
                        .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(otpBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NpasswordCheckBox)
                    .addGroup(ResetEmailLayout.createSequentialGroup()
                        .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewPasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewPassword))
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResetEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ConfirmPassword)
                        .addComponent(CpasswordcheckBox))
                    .addComponent(CPasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        ResetPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ResetPassword.setText("Reset Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResetEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ResetPassword)
                        .addGap(127, 127, 127)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(ResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ResetEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CPasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPasswordBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPasswordBoxActionPerformed

    private void SecurityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecurityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecurityBoxActionPerformed

    private void otpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ForgetPasswordView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPasswordField CPasswordBox;
    private javax.swing.JButton ClickButton;
    private javax.swing.JButton Confirm;
    private javax.swing.JLabel ConfirmPassword;
    private javax.swing.JCheckBox CpasswordcheckBox;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailBox;
    private javax.swing.JLabel NewPassword;
    private javax.swing.JPasswordField NewPasswordBox;
    private javax.swing.JCheckBox NpasswordCheckBox;
    private javax.swing.JPanel ResetEmail;
    private javax.swing.JLabel ResetPassword;
    private javax.swing.JLabel SecurityAnswer;
    private javax.swing.JTextField SecurityAnswerBox;
    private javax.swing.JComboBox<String> SecurityBox;
    private javax.swing.JLabel SecurityQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField otpBox;
    private javax.swing.JButton otpButton;
    // End of variables declaration//GEN-END:variables

   

    // Getters
    public javax.swing.JTextField getemail() {
        return EmailBox;
    }
    public javax.swing.JComboBox<String> getSecurityBox(){
        return SecurityBox;
    }
    
    public javax.swing.JTextField getotpBox(){
        return otpBox;
    }
    public javax.swing.JButton getotpButton(){
        return otpButton;
    }
    public javax.swing.JButton getClickButton(){
        return ClickButton;
    }

    public javax.swing.JTextField getanswer() {
        return SecurityAnswerBox;
    }

    public javax.swing.JPasswordField getnewpass() {
        return NewPasswordBox;
    }

   public javax.swing.JPasswordField getconfirmpass(){
       return CPasswordBox;
   }

   
    
    public javax.swing. JCheckBox getNpasswordCheckbox(){
        return NpasswordCheckBox;
    }
    public javax.swing.JCheckBox getCpasswordCheckbox(){
        return CpasswordcheckBox;
    }
   

   
    // Checkbox toggling
    public void addPasswordToggleListeners(ActionListener npListener, ActionListener cpListener) {
        NpasswordCheckBox.addActionListener(npListener);
        CpasswordcheckBox.addActionListener(cpListener);
    }

    // Attach listeners to Confirm and Back buttons
    public void ChangePass(ActionListener listener) {
        Confirm.addActionListener(listener);
    }

    public void loginBack(ActionListener listener) {
        Back.addActionListener(listener);
    }
    public void sendOtpListener(ActionListener listener){
        otpButton.addActionListener(listener);
    }
    public void verifyOtpListener(ActionListener listener){
      ClickButton.addActionListener(listener);  
    }
    public void enableOtpInputs(){
        otpBox.setEnabled(true);
        ClickButton.setEnabled(true);
    }
    public void enablePasswordInputs(){
        NewPasswordBox.setEnabled(true);
        CPasswordBox.setEnabled(true);
        Confirm.setEnabled(true);
    }
}
